name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  DatasetTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
      - name: Run Code Coverage
        run: |
          pip install wheel
          pip install pytest
          pip install xlrd
          pip install pandas
          pip install pytest-cov
          python -m pytest -q --cmdopt="data/comm_public_2017.xlsx" --cov-report=xml --cov=tests/

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
